artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/19fe2472435f4ad983f7c77ea6cce45b/artifacts
deleted_time: 1776843734548
end_time: 1775649315767
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: 19fe2472435f4ad983f7c77ea6cce45b
run_name: DecisionTreeClassifire
source_name: ''
source_type: 4
source_version: ''
start_time: 1775649315344
status: 4
tags: []
user_id: root
