artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/a2e8c8c28c61410a966f44436e64302e/artifacts
end_time: 1776839180934
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a2e8c8c28c61410a966f44436e64302e
run_name: Voting_Ensemble_SVM_NB_Tree
source_name: ''
source_type: 4
source_version: ''
start_time: 1776839171503
status: 3
tags: []
user_id: root
