artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/6c8e1f0321d14702b928a0e5dff6beb9/artifacts
end_time: 1776251088859
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6c8e1f0321d14702b928a0e5dff6beb9
run_name: DecisionTreeClassifire std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776251088462
status: 4
tags: []
user_id: root
