artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/ebf9c3d2e5c24069a24163f5e36bb5ae/artifacts
end_time: 1776251380998
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ebf9c3d2e5c24069a24163f5e36bb5ae
run_name: DecisionTreeClassifire std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776251375092
status: 3
tags: []
user_id: root
