artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/27815af03f2a4a79a4f64b3f0fa81264/artifacts
end_time: 1775648590986
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 27815af03f2a4a79a4f64b3f0fa81264
run_name: KNN_GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1775648584762
status: 3
tags: []
user_id: root
