artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/ba4ad72218a14d64a3ee511f63ced7fe/artifacts
end_time: 1777425238534
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ba4ad72218a14d64a3ee511f63ced7fe
run_name: Bossting_std
source_name: ''
source_type: 4
source_version: ''
start_time: 1777425231689
status: 3
tags: []
user_id: root
