artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/d686c5f72d9b4465a076ce8c2527f161/artifacts
end_time: 1776249851984
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d686c5f72d9b4465a076ce8c2527f161
run_name: KNN_GridSearch std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776249845908
status: 3
tags: []
user_id: root
