artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/6753c3c7bcb34906889a449af5031caa/artifacts
end_time: 1775630228194
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6753c3c7bcb34906889a449af5031caa
run_name: KNN_GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1775630212722
status: 3
tags: []
user_id: root
