artifact_location: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0
creation_time: 1775628258909
experiment_id: '0'
last_update_time: 1775628258909
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
