artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/238b58ae496449b988c40f49cf8f3250/artifacts
end_time: 1776249017511
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 238b58ae496449b988c40f49cf8f3250
run_name: LogReg_RandomSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1776249017136
status: 4
tags: []
user_id: root
