artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/eae93db0417c4e78805a10ede44b1092/artifacts
end_time: 1776251061035
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: eae93db0417c4e78805a10ede44b1092
run_name: DecisionTreeClassifire std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776251060658
status: 4
tags: []
user_id: root
