artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/30ca1f45a4f94ccd9481ed5f09811328/artifacts
end_time: 1776839204031
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 30ca1f45a4f94ccd9481ed5f09811328
run_name: Voting_Ensemble_SVM_NB_Tree
source_name: ''
source_type: 4
source_version: ''
start_time: 1776839194077
status: 3
tags: []
user_id: root
