artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/a6982f83bced4bcfb211c396a9893a5d/artifacts
end_time: 1775648384671
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a6982f83bced4bcfb211c396a9893a5d
run_name: KNN_GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1775648380116
status: 3
tags: []
user_id: root
