artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/a223e3a5183d4e0281560f06ed8ccef0/artifacts
end_time: 1776857215841
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a223e3a5183d4e0281560f06ed8ccef0
run_name: Bagging_SVM_std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776857210751
status: 3
tags: []
user_id: root
