artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/4a361c9038e64851ba3dbd6a6de8a74c/artifacts
end_time: 1776838139892
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4a361c9038e64851ba3dbd6a6de8a74c
run_name: GaussianNB
source_name: ''
source_type: 4
source_version: ''
start_time: 1776838134170
status: 3
tags: []
user_id: root
