artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/bde654bbe36946999b9d12f568f0956d/artifacts
end_time: 1776251103280
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bde654bbe36946999b9d12f568f0956d
run_name: DecisionTreeClassifire std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776251102481
status: 4
tags: []
user_id: root
