artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/35dca28587494aac9b9e647d772779a5/artifacts
end_time: 1776857606859
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 35dca28587494aac9b9e647d772779a5
run_name: Bagging_SVM_normal
source_name: ''
source_type: 4
source_version: ''
start_time: 1776857600335
status: 3
tags: []
user_id: root
