artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/93be34c7387049b68b43cb5e0cfb2664/artifacts
end_time: 1775649447461
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 93be34c7387049b68b43cb5e0cfb2664
run_name: DecisionTreeClassifire
source_name: ''
source_type: 4
source_version: ''
start_time: 1775649447133
status: 4
tags: []
user_id: root
