artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/81b8cb5f72ff4f7f88ea6e3f5f07e35b/artifacts
end_time: 1776857325709
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 81b8cb5f72ff4f7f88ea6e3f5f07e35b
run_name: Bagging_SVM_std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776857320691
status: 3
tags: []
user_id: root
