artifact_location: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/models/m-5723f240e41a4f269e6ee4c6d03969ec/artifacts
creation_timestamp: 1776249122244
experiment_id: '0'
last_updated_timestamp: 1776249131033
model_id: m-5723f240e41a4f269e6ee4c6d03969ec
model_type: null
name: model
source_run_id: 9eef8c8d447949d297b83dee2554ff00
status: 2
status_message: null
