artifact_uri: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/4164f31ccb2a4e7faa42face41312c2f/artifacts
end_time: 1776250315570
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4164f31ccb2a4e7faa42face41312c2f
run_name: SVM_GridSearch std
source_name: ''
source_type: 4
source_version: ''
start_time: 1776250308896
status: 3
tags: []
user_id: root
