artifact_location: file:///content/drive/MyDrive/Colab_Notebooks/mlflow_experiments/0/models/m-f73dd664f2d547e7ada8f0a2a1f53777/artifacts
creation_timestamp: 1775648639451
experiment_id: '0'
last_updated_timestamp: 1775648644419
model_id: m-f73dd664f2d547e7ada8f0a2a1f53777
model_type: null
name: model
source_run_id: aff03d7a38eb4ea685c948287c01a46c
status: 2
status_message: null
